######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 7 12:00:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += GLWidget.h MainWindow.h Polygon.h Vec3.h Generator.h
SOURCES += GLWidget.cpp main.cpp MainWindow.cpp Polygon.cpp Vec3.cpp Generator.cpp
