######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 7 12:00:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
CONFIG += qt debug

# Input
HEADERS += src/*.h

SOURCES += src/*.cpp

OBJECTS_DIR = obj
MOC_DIR = obj
